### PR TITLE
Enable e2e tests

### PR DESCRIPTION
**Pull request by clkao**
The infrastructure for running tests in actual browsers

### CODE REVIEW

**Comment by karissa** [comment]
i think this has some commits from the styles branch and that's why github doesn't like the merge.

**Comment by clkao** [comment]
Ya i was just testing it locally but I think I accidentally pushed. fixing

**Comment by clkao** [comment]
preliminary tests show that concurrent browser sessions on saucelabs can't see each other as peers.  Will investigate.

**Comment by karissa** [comment]
how's this going? @maxogden suggested we use electron-spawn if saucelabs isn't working right. i'm also okay to have simple e2e testing now and go for the fancy multi-browser stuff a bit later once we have more users testing it

**Comment by clkao** [comment]
It seems `electron-spawn` is for running a js file, but we need to work with a full browser for the e2e part to be meaningful.  playing with nightwatch's phantomjs support now

**Comment by clkao** [comment]
Woot: https://travis-ci.org/datproject/dat.land/jobs/146372220

Turns out using headless chrome is a lot simpler.  We don't get the fancy video recording though, but nightwatch does come with screenshots when tests fail, and we can write some plugin to post the screenshot to PR if necessary.

Going to merge this and create separate issues for e2e improvements.

**Pull request merged**
