### PR TITLE
Sparse mode: preview now gets contents on demand.

### LINKED ISSUE #274: client app should be sparse mode

### PR DESCRIPTION
**Pull request by clkao**
Closes #274

### CODE REVIEW

**Comment by juliangruber** [comment]
are we sure we don't want to by default seed everything, just so we have more peers? maybe there's some reasoning behind this that i didn't see

**Comment by karissa** [comment]
If the files are big it will significantly slow down the browser and eat memory they might not even use

**Comment by clkao** [comment]
There should be a way to toggle the behaviour, and we can decide on the default behaviour based on archive or file size.

**Comment by karissa** [comment]
Yeah that sounds like a pretty good long term solution.
+1 to merging this now

**Pull request merged**
