### PR TITLE
server render the metadata

### PR DESCRIPTION
**Pull request by karissa**
cc @laurengarcia

### CODE REVIEW

**Comment by laurengarcia** [comment]
looks fine, but if user (developer) has the `electron-webrtc` module installed, Haus is going to use that still, isn't it? lets either nuke it or parameterize it <-- i don't care either way, but the way it is now it is very ambiguous.

**Comment by karissa** [comment]
I took out the electron-wrtc part in a separate commit. It needs more thought in `haus.js` and probably should use `hybrid-swarm` or a variation that can handle multiple keys, if we are going to use wrtc in the backend.

**Comment by laurengarcia** [comment]
ok im cool with this then.

**Comment by karissa** [comment]
@laurengarcia okay merged, wondering how it's coming on  the archive api with those two methods that will abstract out the stream transport type?

**Pull request merged**
