### PR TITLE
add browser warning when using an incompatible browser

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by karissa** [comment]
It's not perfect to the design yet but it works.

screen shot 2016-09-01 at 6 37 52 pm

**Comment by karissa** [comment]
I just refactored it a bit, it isn't ready. doesn't work right now because the element `#browser-warning` doesn't stay around, not sure why

**Comment by karissa** [comment]
just refactored it and it doesn't work yet completely, the `#browser-warning` element is getting destroyed somehow

**Comment by laurengarcia** [comment]
we aren't serving up static assets from /client dir, that could be the issue. static assets should either go into the bundle or be served from /public dir so we can CDN-infy /public at some point. I need to set up a real static asset system, see #177 .

**Comment by karissa** [comment]
ok cool /public it is then

**Comment by karissa** [comment]
just in case the bundle fails for some reason on older browsers we can guarantee they're getting the browser incompat message

**Comment by karissa** [comment]
okay, I put it in public/js and now it works on safari <10

**Comment by karissa** [comment]
i messed up this pr so going to rebase off of a new branch

**Pull request closed without merging**
