### PR TITLE
Header styles

### LINKED ISSUE #158: Style intro tour
Needs some layout fixes and dat colors/fonts.
Current status:
image

### PR DESCRIPTION
**Pull request by Kriesse**
Clean up header styles, style intro tour. This closes #158.

### CODE REVIEW

**Comment by karissa** [comment]
Looks great! A couple things:

1. Do you think 'help' should have a big word or just be a question mark? 
2. Should the dat-data logo should go to the landing page instead of dat-data.com?
3. Should we think a bit more about the landing page in relation to the desktop app/cli? We talked about having a few example datasets (until we have user accounts/search/persistent data)... maybe those could go on dat.land?

**Comment by clkao** [comment]
woot, looks pretty awesome!  for (1) I think we can have question mark and ransition to "Help" when hovered?

**Comment by Kriesse** [comment]
re: 1: Yup, it can be more subtle, I'll work on @clkao's suggestion of the transition from "?" to "Help"
re: 2: Let's have it point to the landing page! This tripped me over a few times already.
re: 3: Yes, would be cool to have some existing datasets on there. Let's discuss in a separate issue and collect what we need (and what we can have in a few days): #223

**Comment by laurengarcia** [comment]
Looks great, especially the help component. more comments:
4: "CREATE NEW DAT" button only looks like a button in its hover state to me, so its a little confusing, especially because it is next to the "ENTER DAT LINK" input 
5: the proximity of "create" and "enter dat link" makes me feel that there needs to be some simple disambiguation. 

suggestion: make "CREATE NEW DAT" button lighter (same color as "help" button), leave darker state for hover state, and then put a lowercase "or" between that button and the "ENTER DAT LINK" input. so horizontally, it basically reads "CREATE NEW DAT or ENTER DAT LINK".

**Comment by Kriesse** [comment]
Merged to move forward; filed separate issues for the remaining problems.

**Pull request merged**
